src/app/globals.css
테일윈드 내 커스텀 컬러 및 sr-only 추가
resolves #3
=> 🎨 Feat: 기능 추가, 변경

src/app/layout.tsx
=> 🐛 Fix: 경로 수정

api/bruno/team/final/final/bruno.json, api/bruno/team/final/final/collection.bru, api/bruno/team/final/final/environments/final.bru, api/bruno/team/final/final/회원 목록 조회.bru, src/types/User.ts, src/types/api.ts, src/utils/getUsers.ts
- bruno 초기 설정 및 컬렉션 생성
- 회원 목록 조회를 위한 type 및 서버 함수 생성
resolves #13
=> 🎨 feat: bruno 초기 설정, api 호출 테스트

src/components/common/MobileHeader.tsx
- 헤더에 배경이 없는 것 수정
- 스크롤을 내리고 메뉴를 눌렀을 때 메뉴가 absolute라서 최상단에 뜨는 오류 수정
resolves #24
=> 🐛 fix: 헤더 모바일 버전 버그 해결

api/bruno/team/final/final/공지게시판 목록 조회.bru, api/bruno/team/final/final/문의게시판 목록 조회.bru, api/bruno/team/final/final/문의게시판 상세 조회.bru, api/bruno/team/final/final/자유게시판 목록 조회.bru, api/bruno/team/final/final/회원 상세 조회.bru, api/dbinit/team/data.js, src/app/apitest/page.tsx, src/types/Post.ts, src/utils/getPosts.ts
=> 🎨 feat: 문의, 공지, 커뮤니티 게시판 목록 조회 fetching

next.config.ts, package-lock.json, package.json, src/app/(user)/signup/AgreementSection.tsx, src/app/(user)/signup/BirthdayField.tsx, src/app/(user)/signup/EmailField.tsx, src/app/(user)/signup/NameField.tsx, src/app/(user)/signup/PasswordConfirmField.tsx, src/app/(user)/signup/PasswordField.tsx, src/app/(user)/signup/PhoneField.tsx, src/app/(user)/signup/ProfileImageField.tsx, src/app/(user)/signup/SignupForm.tsx, src/app/(user)/signup/page.tsx, src/data/actions/file.ts, src/data/actions/user.ts, src/types/User.ts, src/types/file.ts, src/types/index.ts
=> 🎨feat: 회원가입 페이지

src/utils/getProducts.ts
=> 🐛 fix: url 쿼리 문자열 오타 수정

api/bruno/team/final/final/게시글 삭제.bru, api/bruno/team/final/final/로그인.bru, src/actions/post.ts, src/app/board/community/new/ImagePostForm.tsx, src/app/board/community/page.tsx, src/app/board/qna/new/NewQnaForm.tsx, src/app/board/qna/new/ProductSearchModal.tsx, src/types/Post.ts
라우팅 경로 해결, bruno 파일 추가, 배포 에러 해결 
resolves #84
=> 🐛 fix: 배포 에러 해결 

src/app/category/CategoryPage.tsx
최신순, 인기순, 낮은가격순, 높은가격순 정렬 기능 추가
resolves #103
=> 🎨 feat: 정렬 기능 추가

api/bruno/team/final/final/게시물 등록.bru, api/bruno/team/final/final/로그인.bru, src/actions/post.ts, src/app/board/qna/QnaWriteButton.tsx, src/app/board/qna/new/NewQnaForm.tsx, src/app/board/qna/page.tsx, src/app/mypage/logout/page.tsx, src/hooks/useHasHydrated.tsx
=> 🎨 feat: 문의 게시판 기능 추가

src/app/board/community/CommunityPostCard.tsx, src/app/board/community/ImageModal.tsx, src/data/actions/addBookmark.ts
=> 🎨 feat: 자유게시판 이미지 클릭시 모달 기능 추가

src/app/board/qna/new/NewQnaForm.tsx
- 상품 이미지 경로, 상품 이름 넘기는 hidden input 추가
resolves #118
=> ♻️ refactor: 타입 수정

src/app/board/notice/[id]/DesktopNoticeDetail.tsx, src/app/board/notice/[id]/MobileNoticeDetail.tsx, src/app/board/notice/[id]/page.tsx, src/app/board/qna/[id]/DesktopQNADetail.tsx, src/app/board/qna/[id]/MobileQNADetail.tsx, src/app/board/qna/[id]/page.tsx, src/app/board/qna/page.tsx, src/app/category/CategoryPage.tsx, src/app/search/layout.tsx, src/app/search/page.tsx, src/components/common/DesktopHeader.tsx, src/components/common/MobileHeader.tsx, src/components/common/NotificationIcon.tsx, src/types/Product.ts
=> ♻️ refactor: 코드 리팩토링

src/app/board/qna/page.tsx, src/types/Post.ts
=> 🎨 문의 게시판 이미지 추가

src/app/(user)/login/page.tsx, src/app/board/qna/QnaWriteButton.tsx, src/app/board/qna/page.tsx, src/hooks/useToggleBookmark.ts
=> 🎨 feat: 비로그인 상태에서 라우팅 로직 변경

src/components/common/ProductCard.tsx, src/components/main/CategorySlider.tsx
인기 상품에 링크 걸기, 카드에 호버 애니메이션 효과 넣기
resolves #129
=> 🎨 feat: 인기 상품에 링크 걸기, 카드에 호버 애니메이션 효과 넣기

src/components/common/Pagination.tsx
=> 💄 style: 페이지 번호 버튼 스타일 변경

api/bruno/team/final/final/파일 업로드 조회.bru, src/app/board/community/CommunityPostCard.tsx, src/app/board/community/new/ImagePostForm.tsx, src/app/board/community/new/page.tsx, src/app/board/qna/new/NewQnaForm.tsx, src/app/board/qna/new/page.tsx
=> 🎨 feat: 자유게시판 글 작성 페이지 기능 추가

src/components/common/DesktopHeader.tsx
=> 🎨 feat: 헤더 컴포넌트 hover 로직 추가

api/bruno/team/final/final/게시글 댓글 조회.bru, api/bruno/team/final/final/게시글 댓글 추가.bru, src/app/apitest/page.tsx, src/app/board/community/CommunityPostCard.tsx, src/app/board/community/ImageModal.tsx, src/components/icon/CommentIcon.tsx, src/data/actions/post.ts
=> 🎨 feat: 자유게시판 댓글 기능 구현

src/app/board/community/CommunityBoardClientWrapper.tsx, src/app/board/community/page.tsx, src/data/actions/post.ts
=> 🎨 feat: 페이지네이션 및 검색탭 기능 추가

src/app/board/notice/NoticeBoardClientWrapper.tsx, src/app/board/notice/page.tsx
=> 🎨 feat: 공지 게시판 검색, 페이지네이션 기능 추가

src/app/paytest/page.tsx, src/components/common/NotificationIcon.tsx, src/stores/notificationStore.ts, src/stores/userStore.ts
알림 수신 방식 변경
- 알림을 보낼 때, zustand로 전역 변수 업데이트
resolves #151
=> 🎨 feat: 알림 수신 방식을 polling에서 상태 기반으로 개선

api/bruno/team/final/final/게시물 수정.bru, src/app/board/qna/QnaBoardClientWrapper.tsx, src/app/board/qna/[id]/DesktopQNADetail.tsx, src/app/board/qna/[id]/MobileQNADetail.tsx, src/app/board/qna/[id]/QNADetailClient.tsx, src/app/board/qna/[id]/page.tsx, src/app/board/qna/edit/[id]/EditQnaForm.tsx, src/app/board/qna/edit/[id]/page.tsx, src/data/actions/post.ts, src/types/Post.ts
=> 🎨 feat: 문의 상세 페이지 리팩토링 및 문의 수정 서버 액션 추가

src/app/products/[id]/PurchaseSection.tsx, src/app/products/[id]/review/ReviewItem.tsx, src/app/products/[id]/review/index.tsx
=> 💄style: 상품 상세 스타일 조정

src/app/apitest/page.tsx, src/app/board/community/page.tsx, src/app/board/notice/page.tsx, src/app/board/qna/page.tsx
=> 🐛 fix: 동적 생성 에러 해결 (SSR)

src/app/mypage/MypageInfo.tsx
=> 💄 style: 관리자 계정 마이페이지 UI 제작

src/app/products/[id]/ProductDetailPage.tsx, src/app/products/[id]/RelatedProducts.tsx, src/components/common/ProductCard.tsx
=> 🎨 feat: 연관상품 기능 추가

src/app/board/community/CommunityBoardClientWrapper.tsx, src/app/board/community/ImageModal.tsx, src/app/board/notice/NoticeBoardClientWrapper.tsx, src/app/board/qna/QnaBoardClientWrapper.tsx, src/app/board/qna/new/NewQnaForm.tsx
=> 💄style: 반응형 디자인 수정 

api/bruno/team/final/final/통계 조회(상품별).bru, api/bruno/team/final/final/통계 조회(일별).bru, src/app/mypage/stats/StatsClient.tsx, src/app/mypage/stats/page.tsx, src/types/stats.ts, src/utils/getStats.ts
=> 🎨 feat: 관리자 통계 조회를 위한 페이지 생성

src/components/common/DesktopHeader.tsx
=> 🎨 feat: 데스크탑 헤더 자동완성 기능 추가

api/bruno/team/02_일반 회원/06_알림메세지/folder.bru, api/bruno/team/02_일반 회원/06_알림메세지/내 알림 목록 조회.bru, api/bruno/team/02_일반 회원/06_알림메세지/알림 메세지 읽음.bru, api/bruno/team/02_일반 회원/06_알림메세지/알림 메시지 보내기.bru, api/bruno/team/02_일반 회원/06_알림메세지/알림 메시지 삭제.bru, api/bruno/team/02_일반 회원/folder.bru, api/bruno/team/05_게시판(QnA, 공지 등)/folder.bru, api/bruno/team/06_시스템/folder.bru, api/bruno/team/console.10g/folder.bru, api/bruno/team/final/folder.bru, api/dbinit/team/data.js, src/app/board/community/CommunityBoardClientWrapper.tsx, src/app/board/community/CommunityWriteButton.tsx, src/app/board/community/page.tsx, src/app/board/notice/NoticeBoardClientWrapper.tsx, src/app/board/notice/page.tsx, src/app/board/qna/QnaBoardClientWrapper.tsx, src/app/board/qna/QnaWriteButton.tsx, src/app/board/qna/page.tsx, src/app/cart/page.tsx, src/app/category/CategoryPage.tsx, src/app/order/page.tsx, src/app/story/[slug]/story-content.tsx, src/components/common/Breadcrumb.tsx
게시판 UI 변경
브레드크럼 UI 통일
DB 관련 작업들 push
resolves #206
=> 💄 style: 게시판 UI 일부 변경

src/app/board/qna/[id]/DesktopQNADetail.tsx, src/app/board/qna/[id]/MobileQNADetail.tsx
=> 🎨 feat: 문의게시판 관리자 답변 달기 기능 추가(desktop, mobile)

src/app/category/CategoryPage.tsx, src/stores/loginStore.ts
=> 🐛 fix: 잘못 머지된 사항 해결

src/app/mypage/MypageInfo.tsx, src/app/mypage/ResidentCard.tsx, src/app/mypage/edit-admin/page.tsx, src/components/common/NotificationIcon.tsx, src/data/actions/authorization.ts, src/stores/loginStore.ts, src/types/User.ts
마이페이지 이미지가 수정이 안되는 버그, 알림 이미지가 안보이는 버그 해결
관리자 정보 수정 페이지 구현
resolves #228
=> 🐛 fix: 마이페이지 이미지가 수정이 안되는 버그, 알림 이미지가 안보이는 버그 해결

src/app/board/community/CommunityPostCard.tsx, src/app/board/community/ImageModal.tsx, src/app/board/qna/QnaBoardClientWrapper.tsx, src/app/board/qna/[id]/DesktopQNADetail.tsx, src/app/board/qna/[id]/MobileQNADetail.tsx, src/app/board/qna/new/NewQnaForm.tsx, src/app/board/qna/new/OrderModal.tsx, src/app/board/qna/new/ProductSearchModal.tsx, src/data/actions/post.ts, src/types/Product.ts
=> 🎨 feat: 이미지 업로드 경로 관련 수정 작업

src/app/board/community/CommunityPostCard.tsx, src/app/board/community/ImageModal.tsx
=> 🎨 feat: typeof로 타입 가드

src/app/board/community/CommunityPostCard.tsx, src/app/board/community/ImageModal.tsx, src/app/board/qna/[id]/DesktopQNADetail.tsx, src/app/board/qna/[id]/MobileQNADetail.tsx, src/data/actions/post.ts
=> 🎨 feat: 자유게시판 삭제 기능 추가

src/app/admin/products/create/ProductCreateForm.tsx, src/app/admin/products/create/page.tsx, src/app/admin/products/edit/[id]/ProductEditPage.tsx, src/app/unauthorized/page.tsx, src/stores/loginStore.ts
=> ♻️ refactor: admin/products 접근 권한 제어

src/app/(user)/signup/EmailField.tsx, src/app/admin/products/create/ProductCreateForm.tsx, src/components/main/CategorySlider.tsx
=> 🐛 fix: 카테고리 슬라이더에 링크 추가

src/app/mypage/AdminGraph.tsx, src/app/mypage/AdminList.tsx, src/app/mypage/MypageInfo.tsx, src/app/mypage/MypageSection.tsx, src/components/common/DesktopHeader.tsx, src/components/common/MobileHeader.tsx, src/components/common/NotificationIcon.tsx
모바일 반응형 구현
마이페이지 UI 수정
resolves #245
=> 💄 style: 관리자 마이페이지 수정

src/components/common/Pagination.tsx, src/components/main/BestReviewCard.tsx
=> 💄 style: 페이지네이션 포인터 추가

src/app/messagetest/page.tsx, src/app/mypage/OrderHistory.tsx, src/components/common/NotificationIcon.tsx
=> 🐛 fix: 불필요하게 선언된 변수 삭제

src/app/admin/products/edit/[id]/EditInput.tsx
=> 🐛 fix: 이미지 배열 오류 수정

src/app/board/community/CommunityPostCard.tsx, src/app/board/community/ImageModal.tsx, src/app/board/qna/edit/[id]/EditQnaForm.tsx, src/app/board/qna/new/NewQnaForm.tsx
=> 💄 style: 다크모드 전용 스타일 제거, 🐛 fix: 유저 프로필 이미지 경로 수정

src/app/(user)/login/page.tsx, src/app/mypage/MypageInfo.tsx, src/app/mypage/OrderHistory.tsx, src/app/mypage/ResidentCard.tsx, src/stores/loginStore.ts
불필요한 alert 삭제
주민증 수정
마이페이지 UI 수정
resolves #270
=> 🎨 feat: 주민증 기본 사진 선택 기능

src/app/admin/products/edit/[id]/EditInput.tsx, src/app/products/[id]/PurchaseSection.tsx, src/app/products/[id]/ShoppingGuide.tsx
=> 🔥 remove: 3만원 이상 배송비 무료 로직 삭제

src/app/admin/stats/StatsClient.tsx, src/app/board/notice/new/NoticePostForm.tsx, src/app/board/qna/[id]/DesktopQNADetail.tsx, src/app/board/qna/[id]/MobileQNADetail.tsx, src/app/board/qna/edit/[id]/EditQnaForm.tsx, src/app/board/qna/new/NewQnaForm.tsx
=> 💄 style: 버튼 커서 포인터 일괄 추가

src/app/board/qna/new/NewQnaForm.tsx
=> 💄 style: 문의 폼 타입에 커서 포인터 추가

src/app/client-layout.tsx, src/app/layout.tsx, src/components/common/WelcomeModal.tsx
=> 🎨feat: 모달 추가, 토큰 만료 시 로그아웃

src/data/actions/addReview.ts, src/data/actions/login.ts
=> 🎨 feat: 토큰 만료 기간 설정

README.md, src/components/common/NotificationIcon.tsx
쪽지 이미지가 안나오는 버그 해결
resolves #302
=> 🐛 fix: 쪽지 이미지가 안나오는 버그 해결

src/app/board/community/CommunityBoardClientWrapper.tsx, src/app/board/community/page.tsx
=> 🐛 fix: 불필요한 props 제거

src/app/category/CategoryPage.tsx
=> 🐛 fix: 카테고리 페이지 해당 상품이 없다는 메시지가 나오는 오류 해결

src/app/category/CategoryPage.tsx
=> 🐛 fix: 로그아웃 유저한테 상품이 안뜨는 버그 해결
